_BASE_: [
  '../../datasets/voc.yml',
  '../../runtime.yml',
  './_base_/optimizer_300e_high.yml',
  '../_base_/yolov5u_cspdarknet.yml',
  './_base_/yolov5u_reader_high_aug.yml',
]
depth_mult: 1.0
width_mult: 1.0

log_iter: 50
snapshot_epoch: 5
weights: output/yolov5u_l_60e_voc/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov5u_l_300e_coco.pdparams

epoch: 60
LearningRate:
  base_lr: 0.001 # 0.01
  schedulers:
  - !YOLOv5LRDecay
    max_epochs: 60
    min_lr_ratio: 0.01
  - !ExpWarmup
    epochs: 3

OptimizerBuilder:
  optimizer:
    type: Momentum
    momentum: 0.937
    use_nesterov: True
  regularizer:
    factor: 0.001 # 0.0005 in yolov8
    type: L2

# metric: COCO
# EvalDataset:
#   !COCODataSet
#     image_dir: VOCdevkit/VOC2007/JPEGImages
#     anno_path: voc_test.json
#     dataset_dir: dataset/voc


input_height: &input_height 640
input_width: &input_width 640
input_size: &input_size [*input_height, *input_width]
mosaic_epoch: &mosaic_epoch 50

worker_num: 4
TrainReader:
  sample_transforms:
    - Decode: {}
    - MosaicPerspective: {mosaic_prob: 1.0, target_size: *input_size, scale: 0.9, mixup_prob: 0.1, copy_paste_prob: 0.1}
    - RandomHSV: {hgain: 0.015, sgain: 0.7, vgain: 0.4}
    - RandomFlip: {}
  batch_transforms:
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
    - PadGT: {}
  batch_size: 16 # default 8 gpus, total bs = 128
  shuffle: True
  drop_last: False
  use_shared_memory: True
  collate_batch: True
  mosaic_epoch: *mosaic_epoch
