_BASE_: [
  '../../datasets/coco_detection.yml',
  '../../runtime.yml',
  './_base_/optimizer_300e.yml',
  '../_base_/yolov7u_elannet.yml', # yolov7u
  './_base_/yolov7u_reader.yml',
]
log_iter: 100
snapshot_epoch: 10
weights: output/yolov7u_l_300e_coco/model_final

arch: L
use_implicit: True
ELANFPN:
  for_u6: True


worker_num: 4
TrainReader:
  batch_size: 32 # default 8 gpus, total bs = 256
